### ISSUE TITLE
Periodical check fails on Windows

### ISSUE THREAD

**Issue by cweigel** [EasyinnovaSL/DPFManager#250]
Version 2.4 (Downloaded installer)
OS: Windows 7

A stored periodical check fails with a windows Script host error (see attachment unfortunately in German). Processing the folder manually does work as expected.

freely translated "The system cannot find the file specified"

![dpf_manager_job_fail](https://cloud.githubusercontent.com/assets/13655319/18050866/6e591a36-6df1-11e6-9913-add5e8c240d2.png)

**Comment by victormunoz** [comment]
The line 14 of the rundpf.vbs script is the one that executes the dpfmanager. So it means that the dpfmanager executable is not found (by the windows task scheduler). I think the problem can be caused because the dpfmanager is not in the system path environment variable. Did you check the option "Add aplication directory to your system path" when installing the DPF Manager?

**Comment by cweigel** [comment]
Yes, I checked it during installation and it's in the Users PATH: C:\Program Files\DPF Manager. Also added the path to the SYSTEMS PATH but that did not work either. Perhaps the JRE did not recognize the updated PATH ??? A restart / new login might be required but I am just guessing.

**Comment by victormunoz** [comment]
To be sure you have the dpf manager in the system path, can you run "dpf-manager-console -v" from the cmd?

**Comment by cweigel** [comment]
It's in the PATH :
```
H:\>dpf-manager-console.exe -v
DPF Manager version 2.4
```
Yet the Scheduler just produced the error message again (its trying each day ad 10:36AM CET).

**Comment by Adri7** [comment]
Solved in the last merge.
