### ISSUE TITLE
v2.4 GUI # Report: 1 conforms to baseline, but 0 passed / global score 0%.

### ISSUE THREAD

**Issue by beyo-ra** [EasyinnovaSL/DPFManager#260]
Configuration:
- Implementation checker: TIFF Baseline, TIFF/EP, TIFF/IT, TIFF/IT-P1, TIFF-IT-P2.
- Report: HTML.

Result:
1	conforms to Baseline Profile
0	conforms to Tiff/EP Profile
0	conforms to Tiff/IT Profile
0	conforms to Tiff/IT-1 Profile
0	conforms to Tiff/IT-2 Profile
--- --- ---
0 passed
1 failed
Global score 0%
--- --- ---
Conformance checker	
Baseline	0 errors	0 warnings	
Tiff/EP	41 errors	0 warnings	
Tiff/IT	1 errors	0 warnings	
Tiff/IT-P1	1 errors	0 warnings	
Tiff/IT-P2	1 errors	0 warnings	
Failed
Score 0%

--- --- ---
I assume the score refers to whether or not it passed all checks, but the first impression is that there is something wrong with the report.

**Comment by victormunoz** [comment]
Yes, when all the ISOS are selected, then a file will pass only if it satisfies all of them (which is unlikely to happen). Surely we could make some improvements to avoid confusions about that...

**Comment by victormunoz** [comment]
In the next release (at the end of this month) a message will appear in the configuration wizard to clarify this.

Also, note that, since version 2.5, the DPF manager automatically checks all of the ISOs and informs the user if they are valid for the checked files _even if_ they are not selected. So you don't need to select all the ISOs to be checked in the configuration, but only the ones that are mandatorily required for your acceptance criteria. As said, all of this will be explained more clearly in the next release.
