### ISSUE TITLE
windows-version 3.0 drop-down-menus: freeze by click

### ISSUE THREAD

**Issue by StefanRohdeEnslin** [EasyinnovaSL/DPFManager#334]
Whenever I open a drop-down menu (necessary for conformance checker, for periodical checks and for adding rules to policy checker) the program freezes.
Looks like an issue we had before: #256. Also the little triangle behind "english" (right-bottom) lets the program freeze.
I use Windows 10, Java is 8 update 11

**Comment by victormunoz** [comment]
Are you using the "lite" version?

**Comment by StefanRohdeEnslin** [comment]
No, not the lite version

**Comment by victormunoz** [comment]
We finally have been able to reproduce this problem!
It sesms to happen only in Windows 10 with touch screens.
This is an issue of JavaFX: https://bugs.openjdk.java.net/browse/JDK-8132897

Fortunatelly, there seems to be some workarounds, while the issue is not fixed: http://stackoverflow.com/questions/31786980/javafx-windows-10-combobox-error

We are going to make some tests, and if successful, we will include a fix for the next release (tomorrow).
Thank you very much for notifyng this issue!
