### ISSUE TITLE
Remove confusing output in console checker

### ISSUE THREAD

**Issue by cweigel** [EasyinnovaSL/DPFManager#344]
When finished checking with the `dpf-manager-console`  using a config with non-default output there is a misleading message

    Created individual report 'C:\Users\wgl/DPF Manager/reports/20161201/4/1-picture0825.tif'
    Generated report into 'C:\Users\wgl/DPF Manager/reports/20161201/4/'

although the output is correctly created in the output dir specified. Checking the dir specified above the report is also stored there which could create a large storage overhead when checking a lot of files. On the other and, it might seen as a kind of backup solution. Related to issue #343.

**Comment by victormunoz** [comment]
Sure the message is confusing. When an output is specified, the "Generated report into" should display the selected folder instead of the internal one.

Anyway, we believe that keeping the internal backup is good, as it also allows the reports section to show a complete list of all the performed checks.
