### ISSUE TITLE
TIFF-(Implementation|Policy)-Checker 1.0.1 # Cannot build the source code offline.

### ISSUE THREAD

**Issue by beyo-ra** [EasyinnovaSL/DPFManager#368]
Attempt to build from source* on ArchLinux in Virtualbox without Internet connection.
* http://preforma-project.eu/dpfmanager-download.html
  Ubuntu: source code, build environment

Build environment missing Java. Using build environment from verapdf.

```
# mvn -v
# java -version
```
> Apache Maven 3.3.9 (bb52d8502b132ec0a5a3f4c09453c07478323dc5; 2015-11-10T17:41:47+01:00)
> Maven home: ~/verapdf_linux/buildenv/apache-maven-3.3.9
> Java version: 1.7.0_79, vendor: Oracle Corporation
> Java home: ~/verapdf_linux/buildenv/jdk1.7.0_79/jre
> Default locale: en_US, platform encoding: UTF-8
> OS name: "linux", version: "4.8.13-1-arch", arch: "amd64", family: "unix"

`#  cd ~/TIFF-Implementation-Checker\ 1.0.1 # containing: pom.xml src`
`#  cd ~/TIFF-Policy-Checker\ 1.0.1 # containing: pom.xml src`

`# mvn clean install`

>[INFO] Scanning for projects...
>Downloading: https://repo.maven.apache.org/maven2/org/sonatype/plugins/nexus-staging-maven-plugin/1.6.3/nexus-staging-maven-plugin-1.6.3.pom
>
>[ERROR] [ERROR] Some problems were encountered while processing the POMs:
>[WARNING] 'build.plugins.plugin.(groupId:artifactId)' must be unique but found duplicate declaration of plugin org.apache.maven.plugins:maven-javadoc-plugin  @ line 93, column 21
>
> [ERROR] Unresolveable build extension: Plugin org.sonatype.plugins:nexus-staging-maven-plugin:1.6.3 or one of its dependencies could not be resolved: Failed to read artifact descriptor for org.sonatype.plugins:nexus-staging-maven-plugin:jar:1.6.3 @ 
>  @ 
> [ERROR] The build could not read 1 project -> [Help 1]
> [ERROR]   
>[ERROR]   The project com.easyinnova:tiffimplementationchecker:1.0.1 (~/easyinnova_ubuntu/TIFF-Implementation-Checker 1.0.1/pom.xml) has 1 error
> [ERROR]     Unresolveable build extension: Plugin org.sonatype.plugins:nexus-staging-maven-plugin:1.6.3 or one of its dependencies could not be resolved: Failed to read artifact descriptor for org.sonatype.plugins:nexus-staging-maven-plugin:jar:1.6.3: Could not transfer artifact org.sonatype.plugins:nexus-staging-maven-plugin:pom:1.6.3 from/to central (https://repo.maven.apache.org/maven2): repo.maven.apache.org: Name or service not known: Unknown host repo.maven.apache.org: Name or service not known -> [Help 2]
> [ERROR] 
> [ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
> [ERROR] Re-run Maven using the -X switch to enable full debug logging.
> [ERROR] 
> [ERROR] For more information about the errors and possible solutions, please read the following articles:
> [ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/ProjectBuildingException
> [ERROR] [Help 2] http://cwiki.apache.org/confluence/display/MAVEN/PluginManagerException

The same error for the policy checker except for
>[WARNING] 'build.plugins.plugin.(groupId:artifactId)' must be unique but found duplicate declaration of plugin org.apache.maven.plugins:maven-javadoc-plugin  **@ line 94, column 21**
>[ERROR]   The project com.easyinnova:**tiffpolicychecker**:1.0.1 (~/easyinnova_ubuntu/TIFF-**Policy**-Checker 1.0.1/pom.xml) has 1 error

**Comment by victormunoz** [comment]
Yes, sorry, we forgot to put the Java installer in this release 3.1, Still you can find it in the release 3.0.1, it is the same.
There you will find the correct java version needed for this project, which is Java 8 (1.8), instead of Java 7 (1.7).

Anyway, the error you are getting does not seem to be related with the Java version.
It seems that maven is trying to download some dependency thorugh internet.
Did you copy the provided maven repository folder into your local path?

**Comment by beyo-ra** [comment]
I found `maven/conf/setting.xml` which was set to `<localRepository>../../Common/maven/repository</localRepository>` Is that correct? Also cf https://maven.apache.org/guides/mini/guide-configuring-maven.html "Note: The local repository must be an absolute path."

Setting the absolute path to the repository did not work. The easiest method was simply to
`ln -s ~/easyinnova_ubuntu/maven/repository ~/.m2/repository`.

Unfortunately the build still fails See attached logs.

- mvn clean install > [buildfail.txt](https://github.com/EasyinnovaSL/DPFManager/files/711708/buildfail.txt)
- mvn -X clean install > [buildfail_dbg.txt](https://github.com/EasyinnovaSL/DPFManager/files/711709/buildfail_dbg.txt)

**Comment by victormunoz** [comment]
In the provided build zip, you will find a "maven" folder. Inside it there is a "repository" folder.
This is the folder that has to be set in the "localRepository" tag.
For exemple: `<localRepository>/home/victor/Downloads/maven/repository</localRepository>`

You can also explicitly specify to maven that it shall not search dependencies through internet with the tag: `<offline>true</offline>`

Finally, to build the project run `mvn install`

Alternatively you can run `mvn install -Dmaven.javadoc.skip=true -DskipTests -Dgpg.skip` in order to skip javadoc generation (there can be bad encodings in linux) and gpg signing (which needs an additional dependency)

**Comment by victormunoz** [comment]
As commented in the issue #370 a new build zip is available, which explains better the building steps.

**Comment by beyo-ra** [comment]
I downloaded Oracle JDK 1.8 and buildenv09-2017-01-18.

Following the instructions, several questions arose.

Step 1. in `instructions.txt` states
> 1. Check Java version
> 
>   java -version
> 
> If not installed, or the version is lower than 1.8 then Java 8 needs to be installed.
>
> Follow the instructions in OpenJFX zip.

`how-to-install.txt` in OpenJFX zip." states  
> 1. Install OpenJDK .deb
> 
> 2. Copy OpenJFX folder content into the base of the installed JDK.
>  cd openjfx-overlay
>  sudo cp -a * /path/to/java

Extracting the content of the zip file results in
- openjfx-overlay (directory)
- zulu8.17.0.3-jdk8.0.102.deb

OpenJFX is not a deb package, and obviously already extracted.

The instruction to _"Copy OpenJFX folder content into the base of the installed JDK."_ becomes confusing:
- the files already seem to exist in Oracle JavaSDK -- should they be replaced?
- while the files do not exist in the extracted Zulu OpenJDK -- does the instruction refer to the OpenJDK?

I set up both OracleJDK and Zulu OpenJDK.* Building the source now throws a different error.
*Zulu does not have a "db" directory.

> [ERROR] Plugin org.apache.maven.plugins:maven-surefire-plugin:2.12.4 or one of its dependencies could not be resolved: Cannot access central (https://repo.maven.apache.org/maven2) in offline mode and the artifact org.apache.maven.plugins:maven-surefire-plugin:jar:2.12.4 has not been downloaded from it before. -> [Help 1]

- mvn -X clean install > [mavendbg_oraclejdk.txt](https://github.com/EasyinnovaSL/DPFManager/files/717368/mavendbg_oraclejdk.txt)

The debug log registers that Java includes the repository directory. A `find -name "surefire"` in the repository matches
> ./org/apache/maven/surefire
> ./org/apache/maven/surefire/surefire

Furthermore: `mvn install -Dmaven.javadoc.skip=true -DskipTests -Dgpg.skip` did not seem to have any effect.

**Comment by victormunoz** [comment]
A first consideration: Java 8 can be installed either with the **Oracle JDK** or with **Open JDK**. The difference between them is that the Oracle version includes JavaFX, but the Open JDK version does not.

In the build zip we have put the Open JDK. That's why we also need to put an additional folder with the JavaFX libraries to be appended.

The instructions in OpenJFX zip (how-to-install.txt):

  1. Install OpenJDK .deb

This means to install the file zulu8.17.0.3-jdk8.0.102.deb. You can do this by typing:

  `sudo dpkg -i zulu8.17.0.3-jdk8.0.102.deb`

  2. Copy OpenJFX folder content into the base of the installed JDK.

  `cd openjfx-overlay`
  `sudo cp -a * /path/to/java`

This step adds the Java FX libraries (which are not included with the Open JDK). Note that if you installed the Oracle JDK, then the JavaFX libraries don't need to be added because they are already in. You only need to do this step if you install the provided Open JDK. The command `sudo cp -a * /path/to/java` simply copies the files keeping the folder structure.

Finally, the error that you are getting means that one of the required dependencies of the project are not present in your local repository. If you have followed the step 3 of the instructions this should not happen. Please try with the repository folder provided in the file `buildenv09-2017-01-18.zip`

**Comment by beyo-ra** [comment]
I have set the path to the repository both in the global conf and the local 
`mvn -s "path/to/maven.conf.xml" clean install`.

The debug log confirms that the repository is found.
> [DEBUG] Using local repository at ~/easyinnova/build/env09-2017-01-18/repository
> [DEBUG] Using manager EnhancedLocalRepositoryManager with priority 10.0 for ~/easyinnova/build/env09-2017-01-18/repository

What does this warning mean? 
> [WARNING] The POM for org.apache.maven.plugins:maven-surefire-plugin:jar:2.12.4 is missing, no dependency information available

I searched the pom.xml I cannot find any reference to "sunrise" in the file.

**Comment by victormunoz** [comment]
Ok, I can see the problem. It is requesting in your machine version 2.12.4 of the surefire plugin, but the available versions of this library (repository/org/apache/maven/surefire/surefire) are 2.17, 2.19.1 and 2.12 (because these are the ones that are (or were) requested in my Linux machine).

The surefire plugin, as you have seen, is not a dependency of the project, but a dependency of maven itself (it is used in the 'test' phase of the build lifecycle, ...and seems to be required even if you deactivate this phase with the flag '-DskipTests').
I thought that for a given maven version (we are both using 3.3.9) the requested version of this plugin would be the same, but it seems to be not the case.

Fortunately, there is a way to declare versions of the internal maven plugins in the pluginManagement section of the pom.

```
<build>
  <pluginManagement>
   <plugins>
     <plugin>
       <groupId>org.apache.maven.plugins</groupId>
       <artifactId>maven-surefire-plugin</artifactId>
       <version>2.17</version>
     </plugin>
     ...
   </plugins>
 <pluginManagement>
</build>

```
Adding this to the project POM should solve the problem. We will add it for the next release.

**Comment by beyo-ra** [comment]
Added to the pom.xml in src directory
```
<pluginManagement>
  <plugin>
    <groupId>org.apache.maven.plugins</groupId>
    <artifactId>maven-assembly-plugin</artifactId>
    <version>2.17</version>
  </plugin>
</pluginManagement>
```
`[]# mvn -X -s "$build_DIR/maven.conf.xml" clean install`
> [WARNING] The POM for org.apache.maven.plugins:maven-assembly-plugin:jar:2.17 is missing, no dependency information available

The content of directory `env09-2017-01-18/repository/org/apache/maven/plugins/maven-assembly-plugin`
- 2.2-beta-5
- 2.4.1
- 2.17

The content of directory `2.17`
- maven-assembly-plugin-2.17.pom.lastUpdated

I assume there is something missing?

Instead, I added v2.4.1 to the pom.xml in src directory
```
<pluginManagement>
  <plugin>
    <groupId>org.apache.maven.plugins</groupId>
    <artifactId>maven-assembly-plugin</artifactId>
    <version>2.4.1</version>
  </plugin>
</pluginManagement>
```

`[]# mvn -s "$build_DIR/maven.conf.xml" clean install >` [mavend_oraclejdk.txt](https://github.com/EasyinnovaSL/DPFManager/files/724382/mavend_oraclejdk.txt)

> [ERROR] Failed to execute goal org.apache.maven.plugins:maven-javadoc-plugin:2.9.1:jar (attach-javadocs) on project tiffimplementationchecker: MavenReportException: Error while creating archive:

The last error was recreated; the original error was however something like

> [ERROR] Failed to execute goal org.apache.maven.plugins:maven-help-plugin: ...

Executing the build with the previous suggested arguments 
`[]# mvn -X -s "$build_DIR/maven.conf.xml" clean install -Dmaven.javadoc.skip=true -DskipTests -Dgpg.skip >` [mavendbg_oraclejdk.txt](https://github.com/EasyinnovaSL/DPFManager/files/724380/mavendbg_oraclejdk.txt)

The source is compiled successfully and installed to directory `TIFF-Implementation-Checker\ 1.0.1/target`. The compilation however throws some errors and warnings; see debug log.

Now. What would be the easiest way to execute the program? I noticed that it has "no main manifest attribute".

**Comment by victormunoz** [comment]
Regarding the `maven-assembly-plugin`, I am not sure why you added it to the `pluginManagement` section. Did you have a similar problem as with the `surefire` dependency?

If so, then you must specify for this plugin the version that is available in the repository folder. The only version for the maven-assembly-plugin there is 2.4.1 so if you put any other version than this, then the "missing dependency" warning will appear.

Regarding the error with the javadoc plugin, this only appears in Linux machines, because there is some bad character encoding. We will solve this in future releases. However you don't need to build the javadoc documentation (this plugin generates something like this: [http://dpfmanager.org/doc/dpfmanager/conformancechecker/tiff/TiffConformanceChecker.html](http://dpfmanager.org/doc/dpfmanager/conformancechecker/tiff/TiffConformanceChecker.html)). If you turn it off (`-Dmaven.javadoc.skip=true`) then as you have seen this problem does not happen and the project builds successfully.

The errors and warnings that appear in the log are all related with javadoc generation and bad character encoding (always located in the code comments). So they are minor issues. However, we will fix them also in future releases.

Finally, how to run the program:
The build process generates two JARs in the "target" folder, one is "tiffimplementationchecker-1.0.1.jar" and the other is "tiffimplementationchecker-1.0.1-jar-with-dependencies.jar". If you want to run the implementation checker you have to execute the jar with dependencies, with the following command:

`java -jar tiffimplementationchecker-1.0.1-jar-with-dependencies.jar`

If you don't specify any parameter, the program will show a message explaining its required parameters.

The other JAR, without dependencies, will not work if you try to run it alone, because it is to be used for integration with the policy checker and with the DPF Manager. We will have to better explain all this in the documentation...

**Comment by beyo-ra** [comment]
Successfully built the Policy Checker

Confirmed that the same problems as for the Implementation Checker occurs for the Policy Checker build. Likewise it seems that the same errors and warnings are thrown.

-  Policy Checker [mavendbg_oraclejdk.txt](https://github.com/EasyinnovaSL/DPFManager/files/727522/mavendbg_oraclejdk.txt)

Successfully built the Implementation and Policy Checker using OpenJDK Azul
- Implementation Checker [mavendbg_openjdk_azul.txt](https://github.com/EasyinnovaSL/DPFManager/files/727531/mavendbg_openjdk_azul.txt)
- Policy Checker build [mavendbg_openjdk_azul.txt](https://github.com/EasyinnovaSL/DPFManager/files/727534/mavendbg_openjdk_azul.txt)

**Comment by beyo-ra** [comment]
> Regarding the maven-assembly-plugin, I am not sure why you added it to the pluginManagement section. Did you have a similar problem as with the surefire dependency?

Yes, as stated above, the same error as for the surefire plugin is thrown.

> [WARNING] The POM for org.apache.maven.plugins:maven-assembly-plugin:jar:2.17 is missing, no dependency information available

**Comment by beyo-ra** [comment]
**Suggestion**
If wrong parameter is given to the jar file, such as "-h" or "-v", e.g.
`java -jar ./tiffimplementationchecker-1.0.1-jar-with-dependencies.jar -v`

The following error is thrown:

```
java.lang.NullPointerException
        at com.easyinnova.tiff.reader.TiffReader.readFile(TiffReader.java:212)
        at com.easyinnova.Main.main(Main.java:33)
```
Suggest reprinting the original message if not implementing basic support such as -h or -v.

> Input params error.
>   First argument must be the file.
>   Second argument can be the ISO to check. If empty, it checks Baseline TIFF 6.0.

**Comment by beyo-ra** [comment]
**Furthermore**
`[archlinux]# java -jar ./tiffpolicychecker-1.0.1-jar-with-dependencies.jar`
returns

> Input params error.
>   First argument must be the file.
>   Second argument can be the ISO to check. If empty, it checks Baseline TIFF 6.0.

A more helpful message would be preferred. Speaking of, how do I use the `tiffpolicychecker-1.0.1-jar-with-dependencies.jar`?

**Comment by victormunoz** [comment]
Ok. We can improve the parameter validation and help system of these programs.
The available ISOs in the Implementation Checker are:

```
TIFF_Baseline_Core_6_0
TIFF_Baseline_Extended_6_0
TIFF_EP
TiffITProfileChecker
TiffITP1ProfileChecker
TiffITP2ProfileChecker
TIAProfileChecker
```

Regarding the policy checker, we have realised that a fix is needed for it to work.
The main class specified in the pom has to be changed to:
`<mainClass>com.easyinnova.policy_checker.Main</mainClass>`
And the namespace of the main class (the first line in the file "main.java") has to be changed to:
`package com.easyinnova.policy_checker;`
We are going to fix this bug in the upcoming release.
