### ISSUE TITLE
Unable to install Windows-Version on Windows 8.1 Pro

### ISSUE THREAD

**Issue by StefanRohde-Enslin** [EasyinnovaSL/DPFManager#371]
Whenever I try to install DPF Maner on a Windows 8.1 Pro machine I get code 216. Tried several times
Screenshot attached
[error_dpf_159.docx](https://github.com/EasyinnovaSL/DPFManager/files/719160/error_dpf_159.docx)

**Comment by victormunoz** [comment]
I think the problem is that this machine is 32bit, but the DPF Manager installer that includes the Java Virtual Machine has it for 64 bits machines...

You could try with the "lite" installer (which does not include the java virtual machine). But you will need to have Java 8 installed in your computer.

Run `java -version` in the cmd to check if java is installed and its version is 1.8 or higher.
If you don't have Java 8 already installed in your computer, you can download it here (get the Windows x86 version):
http://www.oracle.com/technetwork/java/javase/downloads/jre8-downloads-2133155.html

**Comment by StefanRohde-Enslin** [comment]
Where is this stated at the website that "Windows" means "Windows, 64 bit only", or at least in the installation instructions?

**Comment by victormunoz** [comment]
We will update the documentation since it was not explained.
Thank you!

**Comment by StefanRohde-Enslin** [comment]
Thank you Victor !

Von: Victor Muñoz [mailto:notifications@github.com]
Gesendet: Montag, 23. Januar 2017 10:25
An: EasyinnovaSL/DPFManager
Cc: Rohde-Enslin, Stefan; Author
Betreff: Re: [EasyinnovaSL/DPFManager] Unable to install Windows-Version on Windows 8.1 Pro (#371)


We will update the documentation since it was not explained.
Thank you!

**Comment by StefanRohde-Enslin** [comment]
Dear Victor,

as you may know I am a partner in the preforma network. Just found a blogpost about repairing tiff, written by a colleague from the State Library of Saxonia, that might be of interest for you. The title is in German but the test is in English: https://kulturreste.blogspot.de/2017/01/repairing-tiff-images-preliminary-report.html

Best
Stefan



Von: Victor Muñoz [mailto:notifications@github.com]
Gesendet: Montag, 23. Januar 2017 10:25
An: EasyinnovaSL/DPFManager
Cc: Rohde-Enslin, Stefan; Author
Betreff: Re: [EasyinnovaSL/DPFManager] Unable to install Windows-Version on Windows 8.1 Pro (#371)


We will update the documentation since it was not explained.
Thank you!

**Comment by victormunoz** [comment]
Good post. Thank you for sharing!
