### ISSUE TITLE
Error for encoding descriptive text fields needed

### ISSUE THREAD

**Issue by verwinv** [EasyinnovaSL/DPFManager#391]
TIFF files where a different encoding has been used (in this example: Italian accents) show up as question marks. Issue that the wrong kind of encoding has been used could be shown more clearly.

DPFManager output example: ![outlook](https://cloud.githubusercontent.com/assets/6201005/23792619/0bd1df9a-0588-11e7-9fe8-e1969ce6c95c.jpg)
Bridge output example:
<img width="486" alt="screenshot 2017-03-10 11 47 30" src="https://cloud.githubusercontent.com/assets/6201005/23792632/14a21d4c-0588-11e7-9917-7d0b934fec4a.png">

**Comment by victormunoz** [comment]
Which is the problem exactly?
(I cannot see the contents of your comment)

**Comment by victormunoz** [comment]
Ok. It seems to be related with the issue #380 that was fixed yesterday (this fix will be available in the next release).
If you can send us this file, we will verify that it is working

**Comment by verwinv** [comment]
Thanks Victor. Here's the compressed version I received: https://www.dropbox.com/s/7s7bhcp5e5e5htq/PUV12PRE000029121_0167.tif?dl=0

**Comment by verwinv** [comment]
Another participant in the workshop had the whole description field jumbled - I'll ask for the original file.

![error](https://cloud.githubusercontent.com/assets/6201005/23804988/6316a9e6-05bc-11e7-8a25-ea7957af1d77.png)

**Comment by victormunoz** [comment]
Hi Erwin, the first image, contains an error in the copyright tag, since the IFD tags only accept 7-bit ascii encoded characters. There are other containers that should be used in order to accept other character encodings, like XMP, which accepts UTF8. This image is therefore not baseline compliant.

Regarding the problem with the other image, does any error appear in the error section? If you can send me the file I will review it.

Thank you!

**Comment by verwinv** [comment]
> the first image, contains an error in the copyright tag, since the IFD tags only accept 7-bit ascii encoded characters. There are other containers that should be used in order to accept other character encodings, like XMP, which accepts UTF8. This image is therefore not baseline compliant.

Ok - question is therefor whether this could be indicated visually to the user?

>Regarding the problem with the other image, does any error appear in the error section? If you can send me the file I will review it.

It's an image from @ezellohar - will ask him to comment.

**Comment by ezellohar** [comment]
I took a screenshot of the error, in the IDF tags section you can also see that the 'ImageDescription' tag is filled with '???'
Here's also a gdrive link to the original file
![dpf-err](https://cloud.githubusercontent.com/assets/26378841/23939719/4caf997a-0962-11e7-9e5f-944dc8134de6.png)

**Comment by victormunoz** [comment]
Hello @ezellohar, there is a bug with the ImageDescription tag of this image. It contains a long serie of NULL characters (represented with "?" in the report) and this is not allowed, as the specification says:

> "ASCII fields contain strings terminated with a NUL [...] Only one NUL is allowed between strings [...]"

When you change the image description this tag in Windows properties, this tag is overwritten, and that's why the problem gets solved.

@verwinv what do you mean by "visually" indicating this to the user? Do you mean that instead of a "?" character show another thing? any idea?

**Comment by ezellohar** [comment]
> When you change the image description this tag in Windows properties, this tag is overwritten, and that's why the problem gets solved.

Sure, but the strange thing is the tag is empty to begin with. And gives this error.
If I make it empty from windows properties, I get no error, so why dpfmanager sees an empty field filled with that long serie of null characters?
Also, the metadata fix option can actually fix this? I haven't tried.

**Comment by victormunoz** [comment]
In the starting image, the tag is not "empty". It contains a serie of NUL characters.
When you make it empty from windows properties, then the tag turns truly empty, with no NUL characters.
How was this image created? Maybe the software that created it generated these tags with NULs.
The metadata fixer cannot solve this bug yet..

**Comment by victormunoz** [comment]
A new issue has been created to create a fix for solving encoding issues in future releases: #401
