### ISSUE TITLE
Copy error message to the clipboard with Ctrl-C

### ISSUE THREAD

**Issue by cprando** [EasyinnovaSL/DPFManager#397]
From Roman Král <kralroma@ulib.sk>

I tried dpf manager and one feature I found very nice - when I go with
the mouse to the error, I see the comment to the error with a pointer to
the right norm and page within the norm.

But, I cannot copy this message to the clipboard with Ctrl-C.

How can I retrieve this detailed message?

**Comment by victormunoz** [comment]
You can search for the rule id in the reference page of our website: [http://dpfmanager.org/reference-documentation.html](http://dpfmanager.org/reference-documentation.html). There you will be able to copy all the text normally.

However, we will include an improvement for the next release in order to be able to copy the text from the tooltip in the application itself.

Thank you very much for the suggestion!
