### ISSUE TITLE
File structure IFD0 != Errors location IFD1

### ISSUE THREAD

**Issue by victormunoz** [EasyinnovaSL/DPFManager#480]

**Comment by david-russo** [comment]
Hi Victor,

Is this issue about how the IFD numbering (e.g. IFD0, IFD1) in the HTML report's "File structure" section does not match up with the _location_ information reported under the "Conformance checker" section of the report? If so, is the intention that the File structure's IFD indexes be increased by one so that they do match up (e.g. IFD1, IFD2)?

**Comment by victormunoz** [comment]
Yes, this issue is about this, and yes it could be solved by increasing the IFD indexes, or by decreasing the IFD index in the report.

**Comment by david-russo** [comment]
Thanks Victor, I've submitted a fix.

**Comment by victormunoz** [comment]
Thank you!
